// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::oura_core_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::ouracore::bridging")]
pub mod bridging {
    extern "Rust" {
        type OuraCore;

        #[cxx_name = "createOuraCore"]
        fn create_oura_core(id: usize, data_path: &str) -> Box<OuraCore>;

        #[cxx_name = "buildRequest"]
        fn oura_core_build_request(it_: &mut OuraCore, op: &str, params_json: &str) -> Result<String>;

        #[cxx_name = "decodeEvent"]
        fn oura_core_decode_event(it_: &mut OuraCore, tag: f64, body_hex: &str) -> Result<String>;

        #[cxx_name = "encryptNonce"]
        fn oura_core_encrypt_nonce(it_: &mut OuraCore, key_hex: &str, nonce_hex: &str) -> Result<String>;

        #[cxx_name = "eventName"]
        fn oura_core_event_name(it_: &mut OuraCore, tag: f64) -> Result<String>;

        #[cxx_name = "parseBattery"]
        fn oura_core_parse_battery(it_: &mut OuraCore, frame_hex: &str) -> Result<String>;

        #[cxx_name = "parseDeviceInfo"]
        fn oura_core_parse_device_info(it_: &mut OuraCore, frame_hex: &str) -> Result<String>;

        #[cxx_name = "parseEventBatch"]
        fn oura_core_parse_event_batch(it_: &mut OuraCore, frame_hex: &str) -> Result<String>;

        #[cxx_name = "parsePacket"]
        fn oura_core_parse_packet(it_: &mut OuraCore, frame_hex: &str) -> Result<String>;

        #[cxx_name = "parseProductAscii"]
        fn oura_core_parse_product_ascii(it_: &mut OuraCore, frame_hex: &str) -> Result<String>;
    }
}

fn create_oura_core(id: usize, data_path: &str) -> Box<OuraCore> {
    let ctx = Context::new(id, data_path);
    Box::new(OuraCore::new(ctx))
}

fn oura_core_build_request(it_: &mut OuraCore, op: &str, params_json: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.build_request(op, params_json);
        ret
    })
}

fn oura_core_decode_event(it_: &mut OuraCore, tag: f64, body_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.decode_event(tag, body_hex);
        ret
    })
}

fn oura_core_encrypt_nonce(it_: &mut OuraCore, key_hex: &str, nonce_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.encrypt_nonce(key_hex, nonce_hex);
        ret
    })
}

fn oura_core_event_name(it_: &mut OuraCore, tag: f64) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.event_name(tag);
        ret
    })
}

fn oura_core_parse_battery(it_: &mut OuraCore, frame_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.parse_battery(frame_hex);
        ret
    })
}

fn oura_core_parse_device_info(it_: &mut OuraCore, frame_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.parse_device_info(frame_hex);
        ret
    })
}

fn oura_core_parse_event_batch(it_: &mut OuraCore, frame_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.parse_event_batch(frame_hex);
        ret
    })
}

fn oura_core_parse_packet(it_: &mut OuraCore, frame_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.parse_packet(frame_hex);
        ret
    })
}

fn oura_core_parse_product_ascii(it_: &mut OuraCore, frame_hex: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.parse_product_ascii(frame_hex);
        ret
    })
}


