// Auto generated by Craby. DO NOT EDIT.
// Hash: 46c8f7880da1dbdc
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait OuraCoreSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn build_request(&mut self, op: &str, params_json: &str) -> String;
    fn decode_event(&mut self, tag: Number, body_hex: &str) -> String;
    fn encrypt_nonce(&mut self, key_hex: &str, nonce_hex: &str) -> String;
    fn event_name(&mut self, tag: Number) -> String;
    fn parse_battery(&mut self, frame_hex: &str) -> String;
    fn parse_device_info(&mut self, frame_hex: &str) -> String;
    fn parse_event_batch(&mut self, frame_hex: &str) -> String;
    fn parse_packet(&mut self, frame_hex: &str) -> String;
    fn parse_product_ascii(&mut self, frame_hex: &str) -> String;
}
